---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode 
  labels:
    app:  hdfs
    daemon: namenode 
spec:
  ports:
  - port: 80
    name: webui
    protocol: TCP
    targetPort: 50070
  - port: 8020
    name: namenode
    protocol: TCP
    targetPort: 8020
  selector:
    app: hdfs
    daemon: namenode 
  type: LoadBalancer
