---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app:  hdfs
    daemon: namenode 
  name: hdfs-namenode 
spec:
  replicas: 1
  template:
    metadata:
      name: hdfs-namenode
      labels:
        app: hdfs
        daemon: namenode
    spec:
      serviceAccount: default
      volumes:
        - name: hdfs-namenode
          #emptyDir: {}
          persistentVolumeClaim:
            claimName: hdfs-namenode
      containers:
        - name: namenode
          image: uhopper/hadoop-namenode:2.7.2 
          ports:
            - name: namenode
              containerPort: 8020
            - name: webui
              containerPort: 50070
          env:
            - name: CLUSTER_NAME
              value: hdfs
            - name: MULTIHOMED_NETWORK
              value: "0"
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://hdfs-namenode:8020
            - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
              value: "false"
            - name: HDFS_CONF_dfs_client_use_datanode_hostname
              value: "false"
            - name: HDFS_CONF_dfs_datanode_use_datanode_hostname
              value: "false"
            - name: CORE_CONF_hadoop_proxyuser_root_hosts
              value: "*"
            - name: CORE_CONF_hadoop_proxyuser_root_groups
              value: "*"
            - name: HDFS_CONF_dfs_namenode_rpc___bind___host
              value: "0.0.0.0"
            - name: HDFS_CONF_dfs_namenode_servicerpc___bind___host
              value: "0.0.0.0"
            - name: HDFS_CONF_dfs_namenode_http___bind___host
              value: "0.0.0.0"
            - name: HDFS_CONF_dfs_namenode_https___bind___host
              value: "0.0.0.0"
          volumeMounts:
            - name: hdfs-namenode
              mountPath: /hadoop/dfs/
          livenessProbe:
              tcpSocket:
                port: 8020 
              initialDelaySeconds: 120
              timeoutSeconds: 5
          readinessProbe:
              tcpSocket:
                port: 8020
              timeoutSeconds: 5
          resources:
            requests:
              memory: "4Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "1"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hdfs-namenode 
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: "hdfs"
